import Head from 'next/head'
import { Inter } from 'next/font/google'

import { Form, Button, Container } from 'react-bootstrap'
import { useState } from 'react'
import { useRouter } from 'next/router'
import Navigation from '@/components/Navigation'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const router = useRouter()
  const [collection, setCollection] = useState("")

  const GoToNftPage = (e) => {
    e.preventDefault()
    if (collection !== ""){
        router.push(`/nfts/${collection}`)
    }else{
      router.push(`/nfts/20-mint-typewriter`)
    }
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Container>
        <Navigation/>
        <Form onSubmit={GoToNftPage} >
          {/* <Form.Group className="mb-3" controlId="formBasicEmail">
            <Form.Label>Wallet address</Form.Label>
            <Form.Control type="text" placeholder="Enter wallet adress" />
          </Form.Group> */}

            <Form.Group className="mb-3" controlId="formBasicPassword">
            <Form.Label>Collection adress</Form.Label>
            <Form.Control value={(collection !== null && collection !== undefined ) ? collection : '20-mint-typewriter' } onChange={(e) => setCollection(e.target.value)} type="text" placeholder="Ex: 20-mint-typewriter" />
          </Form.Group>
          <Button variant="primary" type="submit">
            Search Nfts
          </Button>
        
        </Form>
        </Container>
    </>
  )
}
